name: Build
on:
  push:
    branches:
      - v3.3.5_vg
  pull_request:
    branches:
      - v3.3.5_vg
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build -- --pathPrefix="/stac/" --historyMode=hash
      - name: Delete dist/config.js
        run: |
          if [ -f dist/config.js ]; then
            rm dist/config.js
            echo "config.js removed from dist/"
          else
            echo "config.js not found in dist/"
          fi
      - name: Zip distribution folder
        run: zip -r dist.zip dist/
      - name: Upload dist.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-archive
          path: dist.zip


